apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  # namespace: prod
spec:
  selector:
    app: frontend-pod
  ports:
    - protocol: TCP
      port: 80 # The port on which the service will be exposed on each Node
      targetPort: 80 # The port on which your application inside the pod is listening
  type: ClusterIP