name: Initial setup

on:
  push:
    branches:
      - main

jobs:
  demo:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      # - name: Copy Service-deploy directory contents to home
      #   run: cp -r $GITHUB_WORKSPACE/Service-deploy/* ~/Service-deploy/

      # - name: Copy the deployments file into the master node
      #   run:  scp -i /home/ubuntu/cloud-creds/git-runner.pem -r ~/Service-deploy ubuntu@10.0.0.18:/home/ubuntu/

      - name: Setup Ansible
        run: |
          sudo apt-get update -y
          sudo apt install software-properties-common -y
          sudo apt-add-repository --yes --update ppa:ansible/ansible
          sudo apt-get install -y ansible
          ansible --version

      # - name: SSH into Master node and Run the deployent file
      #   run: |
      #     ssh -i ~/cloud-creds/git-runner.pem ubuntu@10.0.0.18 <<  'EOF'
      #     sudo apt-get update -y
      #     cd Service-deploy
      #     kubectl apply -f nginx-pod.yml
      #     EOF
