name: Initial setup

on:
  push:
    branches:
      - main
    paths:
      - Service-deploy/**

jobs:
  demo:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy the deployments file into the Master node
        run:  scp -i /home/ubuntu/cloud-creds/git-runner.pem -r $GITHUB_WORKSPACE/Service-deploy ubuntu@10.0.0.18:/home/ubuntu/

      - name: Setup Ansible
        run: |
          if ! command -v ansible &> /dev/null; then
            echo "Ansible not found, installing..."
            sudo apt-get update -y
            sudo apt install software-properties-common -y
            sudo apt-add-repository --yes --update ppa:ansible/ansible
            sudo apt-get install -y ansible
          else
            echo "Ansible is already installed"
          fi
          ansible --version

      - name: SSH into Master node and Run the deployent file
        run: |
          ssh -i ~/cloud-creds/git-runner.pem ubuntu@10.0.0.18 <<  'EOF'
          sudo apt-get update -y
          cd Service-deploy
          kubectl apply -f web-frontend-deployment.yml -n stage
          kubectl apply -f web-frontend-service.yml -n stage
          EOF
