name: Demo action

on:
  push:
    branches:
      - main

jobs:
  demo:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run a script
        run: echo "Hello, self-hosted runner!"
      
      - name: Move file to home directory
        run: mv $GITHUB_WORKSPACE/Service-deploy ~/


