name: Demo action

on:
  push:
    branches:
      - main

jobs:
  demo:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run a script
        run: echo "Hello, self-hosted runner!"
      
      - name: Copy Service-deploy to remote server
        run: |
          scp -i /home/ubuntu/cloud-creds/git-runner.pem $GITHUB_WORKSPACE/Service-deploy ubuntu@10.0.0.18:/home/ubuntu/
        shell: /usr/bin/bash -e {0}


